export const ADD_USER_DETAILS = 'ADD_USER_DETAILS';
export const DELETE_USER_DETAILS = 'DELETE_USER_DETAILS';
export const ADD_PRODUCTS_DETAILS = 'ADD_PRODUCTS_DETAILS';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const ADD_ORDER_CART = 'ADD_ORDER_CART';

